[project]
name = "discord-bots"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "openai>=2.8.1",
    "xai-sdk>=1.4.0",
]
